apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jfrog-stats.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "jfrog-stats.name" . }}
    helm.sh/chart: {{ include "jfrog-stats.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ tpl (.Files.Glob "resources/*").AsConfig . | indent 2 }}
